#!/bin/busybox ash     
#set -x
askfor_kerneldir()
{
  echo "No (unique) kernel directory found: '$KERNELDIR' !"
  exit 0
}
#set -x
HERE=`pwd`
HERESUB="$(/bin/busybox basename $HERE 2>/dev/null)"
KERNELDIR=""
if [ "$1" != "" ]; then
 HERESUB=$1
else
 echo "must specify kernel version !"
 askfor_kerneldir
fi
KERNELDIR="$HERE/linux-$HERESUB"

PATCHDIR="patches-all"
[ "$2" != "" ] && PATCHDIR="$2"
if ! [ -d $HERE/$PATCHDIR ]; then 
  echo "Directory with patches '$PATCHDIR' dpes not exist "
  exit 127 
fi
KERNELTARBALL=""
if [ -e ./linux-$HERESUB.tar.xz ]; then
  KERNELTARBALL=linux-$HERESUB.tar.xz
elif [ -e ./linux-$HERESUB.tar.bz2  ]; then
  KERNELTARBALL=linux-$HERESUB.tar.bz2
elif [ -e ./linux-$HERESUB.tar.gz  ]; then
  KERNELTARBALL=linux-$HERESUB.tar.gz
elif [ -e ./linux-$HERESUB.tar.lzma ]; then
  KERNELTARBALL=linux-$HERESUB.tar.lzma
fi
#
if [ -d $KERNELDIR ]; then
    echo "Kernel Directory already existent : '$KERNELDIR'"
    echo "Continue with overwriting ? "
    read yesno
    if [ "$yesno" != "y" -a "$yesno" != "Y" ]; then
      exit 127
    fi

fi
#
if [ "$KERNELTARBALL" != "" ]; then
  /bin/busybox tar -xf $HERE/$KERNELTARBALL 2>/dev/null
  RC=$?
else
    echo "No kernel file 'linux-$HERESUB' found or failed to extract!"
    exit 127
fi
/bin/busybox sync
/bin/busybox sleep 1
if [ $RC -ne 0 ]; then 
    echo "Kernel file '$KERNELTARBALL' failed to extract with '$RC'!"
    exit $RC
fi
#
/bin/busybox rm patchings.log
if ! [ -e "$KERNELDIR" ]; then
  VERSION="3."
  KERNELDIR=`/bin/busybox ls -1d $HERE/linux-$VERSION??  2>/dev/null`
  for d in $KERNELDIR; do
    if [ -d $d ]; then
       KERNELDIR=$d
    fi
  done
  if [ "$KERNELDIR" = "" ]; then
    KERNELDIR=`/bin/busybox ls -1d $HERE/linux-$HERESUB  2>/dev/null`
    for d in $KERNELDIR; do
      if [ -d $d ]; then
         KERNELDIR=$d
      fi
    done
  fi
  if [ "$KERNELDIR" = "" ]; then
    echo "No kernel directory  'linux-$HERESUB' found!"
    exit 4
  fi
fi
AUFSDIR="not-existent"
if [ "$3" != "" ]; then 
 AUFSDIR="$HERE/$3"
fi

do_patchset() {

if [ "$AUFSDIR" != "not-existent" ];then
echo " aufs Docu $AUFSDIR --> $KERNELDIR"
/bin/busybox cp -Rv  $AUFSDIR/Documentation/*  $KERNELDIR/Documentation/
echo " aufs fs $AUFSDIR --> $KERNELDIR"
/bin/busybox cp -Rv  $AUFSDIR/fs/*  $KERNELDIR/fs/
echo " aufs include $AUFSDIR --> $KERNELDIR"
/bin/busybox cp -Rv  $AUFSDIR/include/*  $KERNELDIR/include/
fi
local RC

RC=""
if [ -d $HERE/$PATCHDIR ]; then 
  /bin/busybox cp $HERE/$PATCHDIR/DOT.config-*  $KERNELDIR 2>/dev/null
  echo "Additional patches, proprietary and from distros (Fedora,SuSE,ArchLinux,..) -->"
	cd $KERNELDIR
	/bin/busybox find  $HERE/$PATCHDIR -maxdepth 1 | /bin/busybox sort | while read l; do
	  echo "Patching with --->  $l"
	  patch -p1 -F70 < $l
	  RC=$?
	  if [ $RC -gt 0 ]; then echo "ERROR: Failed patching ---> $l with '$RC'"; fi 
	done
  cd $HERE
else
  echo "No patches found under --> '$2' "
fi

}


do_patchset >> patchings.log 2>&1
if [ -e $KERNELDIR/localversion-rt  ]; then
  source /etc/functions-ash-dm  
fi 
cp patchings.log $KERNELDIR/ 
#set +x
exit $?

