#!/bin/busybox ash
#set -x
FN="linux-$1.tar.xz"
! [ -e $FN ] && FN="linux-$1.tar.bz2"
! [ -e $FN ] && FN="linux-$1.tar.gz"
! [ -e $FN ] && exit 5
#FN="linux-3.2.13-full.tar.xz"

source ./functions-ash-dm

if [ "$2" != "" ]; then 
 if [ -d "$2" ]; then PATCHDIR="$2"; fi
fi
if [ "$3" != "" ]; then 
 if [ -d "$3" ]; then AUFSDIR="$3"; fi
fi
if [ "$4" != "" ]; then 
 if [ -d "$4" ]; then RAMDISKDIR="$4"; fi
fi

mkramdisk

if [ "$RAMDISKFS" != "" ]; then
  echoconsole "$0" "copying....."
  /bin/busybox cp -f do-make* $RAMDISKFS
  /bin/busybox cp -f do-setup* $RAMDISKFS
  /bin/busybox cp -f functions-* $RAMDISKFS
  /bin/busybox cp -f makevars* $RAMDISKFS
  /bin/busybox cp -f apply-patches* $RAMDISKFS
  /bin/busybox cp -fR $PATCHDIR  $RAMDISKFS  2>/dev/null
  /bin/busybox cp -fR $AUFSDIR  $RAMDISKFS 2>/dev/null
  /bin/busybox cp -f $FN $RAMDISKFS   2>/dev/null
  echoconsole "$0" ".....done!"
   cd  $RAMDISKFS
  /bin/busybox sync
  #/bin/busybox tar -xf $FN  2>/dev/null
  #RC=$?
else
  echoconsole "$0" "no ramdisk filesystem created!"
fi
#
exit 0
#
