#!/bin/busybox ash
set -x
askfor_patchdir()
{
  echo "No (unique) directory found with files to patch : '$1' "
  echo "Please specify a correct one!"
  exit 127
}

SERIESFILE=""
PATCHDIR=""
NEWPATCHDIR="patches-ordered-ash"
PATCHNAME=""
PATCHNAMENEW=""
PATCHNAMENEW2=""
COUNT=0
PREF="0"
PREFNAME=""
if [ "$3" != "" ]; then   
  PREFIX="$3"
fi
if [ "$2" != "" ]; then   
  SERIESFILE="$2"
  SERIESFILE="$HERE/$SERIESFILE"
fi
if [ "$1" != "" ]; then   
  PATCHDIR="$1"
fi
HERE=`pwd`
HERESUB="$(/bin/busybox basename $HERE 2>/dev/null)"
if [ "$PATCHDIR" != "" ]; then
 HERESUB="$PATCHDIR"
else
 echo "must specify at least a patch directory !"
 askfor_patchdir
fi
set_names()
{
  local pn porig porignew
   porig="$1"
   porignew="$1"
   case "$1" in
     \#*|\n)
       porig=""
     ;;
     Patch*\:*) #Fedora case
       porig=${porig#*: }
     ;;
   esac
   case "$porig" in
     /*|*/*)
       pn=$(/bin/busybox basename "$porig" 2>/dev/null)
       porig=$(/bin/busybox dirname "$porig" 2>/dev/null)
       porignew=$(echo "$porig" | /bin/busybox tr "/" "+" 2>/dev/null)
     ;;
     *)
       pn="$porig"
     ;;
   esac
   PATCHNAME="$pn"
   if [ "$pn" != "$porig" ]; then
     PATCHNAMENEW=${porignew}+${PATCHNAME}
   else
     PATCHNAMENEW=${PATCHNAME}
   fi
}

/bin/busybox mkdir -p $HERE/$NEWPATCHDIR 2>/dev/null
if [ "$PREFIX" != "" ]; then PREFIX=${PREFIX}; fi
if [  "`/bin/busybox ls -1 $HERE/$PATCHDIR`" != "" ]; then
  if [ -d "$HERE/$NEWPATCHDIR" ]; then 
  #
  #SERIESFILES="`/bin/busybox ls -1 $HERE/$PATCHDIR/$SERIESFILE  2>/dev/null`"
  if [ "$SERIESFILE" != "" -a "$3" != "" ]; then
    #for p in `/bin/busybox cat $PATCHDIR/$SERIESFILE`; do
    COUNT=0
    SERIESFILE="$HERE/$SERIESFILE"
    while read p; do
        set_names "$p"
       if [ "${PATCHNAME}" != "" ]; then
        #if [ "$p" = "$PATCHNAME" ]; then cd $HERE/$PATCHDIR; fi
	if [ -f  "$PATCHDIR/$PATCHNAME" ]; then 
	  p="$PATCHDIR/$PATCHNAME"
	fi
	if [ -f  "$PATCHDIR/$p" ]; then 
	  p="$PATCHDIR/$p"
	fi
	if [ -f  "$p" ]; then 
	  echo "Copying ---> $p to $NEWPATCHDIR/$PREFIX-$COUNT-$PATCHNAMENEW : "
	  
	  cp -v  "$p"   $HERE/$NEWPATCHDIR/
	  RC=$?
	  if [ $RC -gt 0 ]; then 
	    echo "ERROR: Failed copying ---> $p with '$RC'" 
	  else
	    if [ $COUNT -lt 10000 ]; then 
	      PREF="0"
	    fi
	    if [ $COUNT -lt 1000 ]; then 
	      PREF="00"
	    fi
	    if [ $COUNT -lt 100 ]; then 
	      PREF="000"
	    fi
	    if [ $COUNT -lt 10 ]; then 
	      PREF="0000"
	    fi
	    mv -f $HERE/$NEWPATCHDIR/"$PATCHNAME"  $HERE/$NEWPATCHDIR/"${PREFIX}-${PREF}${COUNT}-${PATCHNAMENEW}" 
	    COUNT=$(( $COUNT + 1 ))
	  fi 
	fi
        #if [ "$p" = "$PATCHNAME" ]; then cd $HERE; fi
      fi
    #done
    done < $SERIESFILE
  else
     PATCHDIR=$HERE/$PATCHDIR
     COUNT=0
      /bin/busybox find  $PATCHDIR -maxdepth 1 -type f | /bin/busybox sort | while read p; do
          set_names "$p"
 #         PATCHNAME=`check_patchname "$p"`
	  echo "Copying ---> $p to $NEWPATCHDIR/$PREFIX$COUNT-$PATCHNAMENEW : "
	  
	  cp -v  "$p"   $HERE/$NEWPATCHDIR/
	  RC=$?
	  if [ $RC -gt 0 ]; then 
	    echo "ERROR: Failed copying ---> $p with '$RC'" 
	  else
	    if [ $COUNT -lt 10000 ]; then 
	      PREF="0"
	    fi
	    if [ $COUNT -lt 1000 ]; then 
	      PREF="00"
	    fi
	    if [ $COUNT -lt 100 ]; then 
	      PREF="000"
	    fi
	    if [ $COUNT -lt 10 ]; then 
	      PREF="0000"
	    fi
	    if [ "$PREFIX" != "" ]; then
	      PREFNAME=${PREFIX}-${PREF}${COUNT}
	    else
	      PREFNAME=${PREF}${COUNT}
	    fi
	    mv -f "$HERE/$NEWPATCHDIR/"$PATCHNAME   $HERE/$NEWPATCHDIR/${PREFNAME}-${PATCHNAMENEW} 
	    COUNT=$(( $COUNT + 1 ))
	  fi 
	done
	cd $HERE
  fi
  else # TARGETDIR
    echo "Directory  '$TARGETDIR' with tree to patch does not exist "
    exit 127 
  fi
else 
  askfor_patchdir $PATCHDIR
fi

#
